# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e393134ce7bba73b8bd6b6f4d22c844f493224de361cf30f5de402ef31553a41f94026ded736ec226f15a8dec5a77337bacb340ead03d0b0b3657322851c4b6

test:
  secret_key_base: d22f5b11c3ea2fe0cc3f78a2ba5e679abf38627eb24ba844be76b1b183983924933c3c99b62947e82b4c4f5e5cd6c5df3945450682f902ec9ca74a8211c58473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
